# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.

import _geos
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    if method := class_type.__swig_setmethods__.get(name, None):
        return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError(f"You cannot add attributes to {self}")

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    if method := class_type.__swig_getmethods__.get(name, None):
        return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try:
        strthis = f"proxy of {self.this.__repr__()}"
    except: strthis = ""
    return f"<{self.__class__.__module__}.{self.__class__.__name__}; {strthis} >"

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError(f"You cannot add attributes to {self}")

    return set_attr


class PySwigIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _geos.delete_PySwigIterator
    __del__ = lambda self : None;
    def value(self):
        return _geos.PySwigIterator_value(*self)
    def incr(self):
        return _geos.PySwigIterator_incr(*self)
    def decr(self):
        return _geos.PySwigIterator_decr(*self)
    def distance(self):
        return _geos.PySwigIterator_distance(*self)
    def equal(self):
        return _geos.PySwigIterator_equal(*self)
    def copy(self):
        return _geos.PySwigIterator_copy(*self)
    def next(self):
        return _geos.PySwigIterator_next(*self)
    def previous(self):
        return _geos.PySwigIterator_previous(*self)
    def advance(self):
        return _geos.PySwigIterator_advance(*self)
    def __eq__(self):
        return _geos.PySwigIterator___eq__(*self)
    def __ne__(self):
        return _geos.PySwigIterator___ne__(*self)
    def __iadd__(self):
        return _geos.PySwigIterator___iadd__(*self)
    def __isub__(self):
        return _geos.PySwigIterator___isub__(*self)
    def __add__(self):
        return _geos.PySwigIterator___add__(*self)
    def __sub__(self):
        return _geos.PySwigIterator___sub__(*self)
    def __iter__(self): return self
PySwigIterator_swigregister = _geos.PySwigIterator_swigregister
PySwigIterator_swigregister(PySwigIterator)

GEOS_VERSION_MAJOR = _geos.GEOS_VERSION_MAJOR
GEOS_VERSION_MINOR = _geos.GEOS_VERSION_MINOR
GEOS_VERSION = _geos.GEOS_VERSION
GEOS_JTS_PORT = _geos.GEOS_JTS_PORT
GEOS_CAPI_VERSION_MAJOR = _geos.GEOS_CAPI_VERSION_MAJOR
GEOS_CAPI_VERSION_MINOR = _geos.GEOS_CAPI_VERSION_MINOR
GEOS_CAPI_VERSION_PATCH = _geos.GEOS_CAPI_VERSION_PATCH
GEOS_CAPI_FIRST_INTERFACE = _geos.GEOS_CAPI_FIRST_INTERFACE
GEOS_CAPI_LAST_INTERFACE = _geos.GEOS_CAPI_LAST_INTERFACE
GEOS_CAPI_VERSION = _geos.GEOS_CAPI_VERSION
GEOS_POINT = _geos.GEOS_POINT
GEOS_LINESTRING = _geos.GEOS_LINESTRING
GEOS_LINEARRING = _geos.GEOS_LINEARRING
GEOS_POLYGON = _geos.GEOS_POLYGON
GEOS_MULTIPOINT = _geos.GEOS_MULTIPOINT
GEOS_MULTILINESTRING = _geos.GEOS_MULTILINESTRING
GEOS_MULTIPOLYGON = _geos.GEOS_MULTIPOLYGON
GEOS_GEOMETRYCOLLECTION = _geos.GEOS_GEOMETRYCOLLECTION
GEOS_WKB_XDR = _geos.GEOS_WKB_XDR
GEOS_WKB_NDR = _geos.GEOS_WKB_NDR
version = _geos.version
class CoordinateSequence(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _geos.new_CoordinateSequence(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _geos.delete_CoordinateSequence
    __del__ = lambda self : None;
    def clone(self):
        return _geos.CoordinateSequence_clone(*self)
    def setX(self):
        return _geos.CoordinateSequence_setX(*self)
    def setY(self):
        return _geos.CoordinateSequence_setY(*self)
    def setZ(self):
        return _geos.CoordinateSequence_setZ(*self)
    def setOrdinate(self):
        return _geos.CoordinateSequence_setOrdinate(*self)
    def getX(self):
        return _geos.CoordinateSequence_getX(*self)
    def getY(self):
        return _geos.CoordinateSequence_getY(*self)
    def getZ(self):
        return _geos.CoordinateSequence_getZ(*self)
    def getOrdinate(self):
        return _geos.CoordinateSequence_getOrdinate(*self)
    def getSize(self):
        return _geos.CoordinateSequence_getSize(*self)
    def getDimensions(self):
        return _geos.CoordinateSequence_getDimensions(*self)
CoordinateSequence_swigregister = _geos.CoordinateSequence_swigregister
CoordinateSequence_swigregister(CoordinateSequence)

class Geometry(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _geos.delete_Geometry
    __del__ = lambda self : None;
    def clone(self):
        return _geos.Geometry_clone(*self)
    def geomType(self):
        return _geos.Geometry_geomType(*self)
    def typeId(self):
        return _geos.Geometry_typeId(*self)
    def normalize(self):
        return _geos.Geometry_normalize(*self)
    def getSRID(self):
        return _geos.Geometry_getSRID(*self)
    def setSRID(self):
        return _geos.Geometry_setSRID(*self)
    def getDimensions(self):
        return _geos.Geometry_getDimensions(*self)
    def getNumGeometries(self):
        return _geos.Geometry_getNumGeometries(*self)
    def intersection(self):
        return _geos.Geometry_intersection(*self)
    def buffer(self):
        return _geos.Geometry_buffer(*self)
    def convexHull(self):
        return _geos.Geometry_convexHull(*self)
    def difference(self):
        return _geos.Geometry_difference(*self)
    def symDifference(self):
        return _geos.Geometry_symDifference(*self)
    def boundary(self):
        return _geos.Geometry_boundary(*self)
    def union(self):
        return _geos.Geometry_union(*self)
    def pointOnSurface(self):
        return _geos.Geometry_pointOnSurface(*self)
    def getCentroid(self):
        return _geos.Geometry_getCentroid(*self)
    def getEnvelope(self):
        return _geos.Geometry_getEnvelope(*self)
    def relate(self):
        return _geos.Geometry_relate(*self)
    def lineMerge(self):
        return _geos.Geometry_lineMerge(*self)
    def simplify(self):
        return _geos.Geometry_simplify(*self)
    def topologyPreserveSimplify(self):
        return _geos.Geometry_topologyPreserveSimplify(*self)
    def relatePattern(self):
        return _geos.Geometry_relatePattern(*self)
    def disjoint(self):
        return _geos.Geometry_disjoint(*self)
    def touches(self):
        return _geos.Geometry_touches(*self)
    def intersects(self):
        return _geos.Geometry_intersects(*self)
    def crosses(self):
        return _geos.Geometry_crosses(*self)
    def within(self):
        return _geos.Geometry_within(*self)
    def contains(self):
        return _geos.Geometry_contains(*self)
    def overlaps(self):
        return _geos.Geometry_overlaps(*self)
    def equals(self):
        return _geos.Geometry_equals(*self)
    def equalsExact(self):
        return _geos.Geometry_equalsExact(*self)
    def isEmpty(self):
        return _geos.Geometry_isEmpty(*self)
    def isValid(self):
        return _geos.Geometry_isValid(*self)
    def isSimple(self):
        return _geos.Geometry_isSimple(*self)
    def isRing(self):
        return _geos.Geometry_isRing(*self)
    def hasZ(self):
        return _geos.Geometry_hasZ(*self)
    def area(self):
        return _geos.Geometry_area(*self)
    def length(self):
        return _geos.Geometry_length(*self)
    def distance(self):
        return _geos.Geometry_distance(*self)
Geometry_swigregister = _geos.Geometry_swigregister
Geometry_swigregister(Geometry)

class Point(Geometry):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _geos.delete_Point
    __del__ = lambda self : None;
    def getCoordSeq(self):
        return _geos.Point_getCoordSeq(*self)
Point_swigregister = _geos.Point_swigregister
Point_swigregister(Point)

class LineString(Geometry):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _geos.delete_LineString
    __del__ = lambda self : None;
    def getCoordSeq(self):
        return _geos.LineString_getCoordSeq(*self)
LineString_swigregister = _geos.LineString_swigregister
LineString_swigregister(LineString)

class LinearRing(Geometry):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _geos.delete_LinearRing
    __del__ = lambda self : None;
    def getCoordSeq(self):
        return _geos.LinearRing_getCoordSeq(*self)
LinearRing_swigregister = _geos.LinearRing_swigregister
LinearRing_swigregister(LinearRing)

class Polygon(Geometry):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _geos.delete_Polygon
    __del__ = lambda self : None;
    def getExteriorRing(self):
        return _geos.Polygon_getExteriorRing(*self)
    def getNumInteriorRings(self):
        return _geos.Polygon_getNumInteriorRings(*self)
    def getInteriorRingN(self):
        return _geos.Polygon_getInteriorRingN(*self)
Polygon_swigregister = _geos.Polygon_swigregister
Polygon_swigregister(Polygon)

class GeometryCollection(Geometry):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _geos.delete_GeometryCollection
    __del__ = lambda self : None;
    def getGeometryN(self):
        return _geos.GeometryCollection_getGeometryN(*self)
GeometryCollection_swigregister = _geos.GeometryCollection_swigregister
GeometryCollection_swigregister(GeometryCollection)

class MultiPoint(GeometryCollection):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _geos.delete_MultiPoint
    __del__ = lambda self : None;
MultiPoint_swigregister = _geos.MultiPoint_swigregister
MultiPoint_swigregister(MultiPoint)

class MultiLineString(GeometryCollection):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _geos.delete_MultiLineString
    __del__ = lambda self : None;
MultiLineString_swigregister = _geos.MultiLineString_swigregister
MultiLineString_swigregister(MultiLineString)

class MultiLinearRing(GeometryCollection):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _geos.delete_MultiLinearRing
    __del__ = lambda self : None;
MultiLinearRing_swigregister = _geos.MultiLinearRing_swigregister
MultiLinearRing_swigregister(MultiLinearRing)

class MultiPolygon(GeometryCollection):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _geos.delete_MultiPolygon
    __del__ = lambda self : None;
MultiPolygon_swigregister = _geos.MultiPolygon_swigregister
MultiPolygon_swigregister(MultiPolygon)

createPoint = _geos.createPoint
createLineString = _geos.createLineString
createLinearRing = _geos.createLinearRing
createPolygon = _geos.createPolygon
geomFromWKT = _geos.geomFromWKT
geomToWKT = _geos.geomToWKT
getWKBOutputDims = _geos.getWKBOutputDims
setWKBOutputDims = _geos.setWKBOutputDims
getWKBByteOrder = _geos.getWKBByteOrder
setWKBByteOrder = _geos.setWKBByteOrder
geomFromWKB = _geos.geomFromWKB
geomToWKB = _geos.geomToWKB
geomFromHEX = _geos.geomFromHEX
geomToHEX = _geos.geomToHEX


